<a href="https://colab.research.google.com/github/RishiRishwanth/DeepLearning/blob/main/Tensors_%26_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

tensor_zero_d = tf.constant(4) #0D
print(tensor_zero_d)

tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tensor_2d = tf.constant([[2,0,-3],[1,2,3]],dtype=tf.float32)
print(tensor_2d)

tensor_3d = tf.constant([
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]]
])
print(tensor_3d)


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)
tf.Tensor(
[[ 2.  0. -3.]
 [ 1.  2.  3.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[ 2  0 -3]
  [ 1  2  3]]

 [[ 2  0 -3]
  [ 1  2  3]]

 [[ 2  0 -3]
  [ 1  2  3]]

 [[ 2  0 -3]
  [ 1  2  3]]], shape=(4, 2, 3), dtype=int32)


In [7]:
tensor_3d.ndim #says that tensor is 3d

3

In [11]:
tensor_4d = tf.constant([[
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]]
],
                         [
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]]
],
                         [
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]]
],
                         [
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]],
    [[2,0,-3],[1,2,3]]
],
                         ])

print(tensor_4d,tensor_4d.ndim)

tf.Tensor(
[[[[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]]


 [[[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]]


 [[[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]]


 [[[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]

  [[ 2  0 -3]
   [ 1  2  3]]]], shape=(4, 4, 2, 3), dtype=int32) 4


In [16]:
casted_tensor_1d = tf.cast(tensor_one_d,dtype = tf.float64)
print(casted_tensor_1d)
casted_tensor_1d = tf.cast(tensor_one_d,dtype = tf.bool
                           )
print(casted_tensor_1d)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float64)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [18]:
tensor_bool = tf.constant([True,False,True])
casted_tensor = tf.cast(tensor_bool,dtype = tf.int32)
casted_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 0, 1], dtype=int32)>

In [20]:
tensor_string = tf.constant('hello World')
print(tensor_string)


tf.Tensor(b'hello World', shape=(), dtype=string)


In [21]:
import numpy as np

np_array= np.array([1,2,3])
print(np_array)

[1 2 3]


In [28]:
eye_tensor = tf.eye(
                    num_rows = 3,
                    num_columns = 3,
                    batch_shape=[3,],
                    dtype = tf.dtypes.float32,
                    name = None
                    )
print(eye_tensor)
#creates identity matrix



tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(3, 3, 3), dtype=float32)


In [29]:
fill_tensor = tf.fill(
    [3,4],5, name=None
)
print(fill_tensor)
#filling the tensor with 5 in shape (3,4)


tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [32]:
ones_tensor = tf.ones(
    [5,3],
    dtype = tf.dtypes.float32,
    name = None
)
print(f'ones_tensor:{ones_tensor}',ones_tensor)

#ones_like
#takes shape from inpput and fills 1 in the same shape
ones_like_tensor = tf.ones_like(
    tensor_4d, dtype = None, name=None

)
print(ones_like_tensor)



ones_tensor:[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)
tf.Tensor(
[[[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]], shape=(4, 4, 2, 3), dtype=int32)


In [34]:
#rank  = dimenesion,degree...

print(tf.rank(tensor_4d))

tf.Tensor(4, shape=(), dtype=int32)


In [43]:
#random_tensor

#normal and uniform are distributions

random_tensor = tf.random.normal(
    [3,2],
    mean=0.0,
    stddev= 5.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

random_tensor = tf.random.uniform(
    [3,2],
    minval=0.0,
    maxval= 2.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor(
[[ 6.2813845   0.7862251 ]
 [-7.486103    0.36208773]
 [ 6.854948   -3.4289074 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.30317783 0.16604805]
 [0.9537866  1.6966357 ]
 [1.8180356  0.463948  ]], shape=(3, 2), dtype=float32)


In [4]:
#INDEXING = slicing

tensor_indexed = tf.constant([3,6,2,3,4,6,66,7])
print(tensor_indexed[0:3])

tf.Tensor([3 6 2], shape=(3,), dtype=int32)


In [5]:
tf.range(2,6)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [ ]:
#tf.abs -->absolute value
#tf.sqrt
#tf.add,tf.divide..etc..
#tf.math.multiply
#tf.math.argmax
